# Generated by Django 2.0.5 on 2018-11-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField(verbose_name='date joined')),
                ('credits', models.IntegerField(default=0)),
                ('num_transactions', models.IntegerField(default='None', max_length=200)),
            ],
        ),
    ]
