# Generated by Django 2.0.5 on 2018-11-30 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0002_auto_20181201_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_users',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 1, 5, 1, 2, 710161), verbose_name='date joined'),
        ),
    ]
